function output_fei_full(){
document.write("\
<table border=1>\
  <tbody>\
    <tr>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[4]+"</td>\
            <td>宫</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table  border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+wangshuai[9]+"</td>\
            <td>宫</td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+wangshuai[2]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_4>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[4]+"</td>\
            <td>"+liuqin[4]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[4]+"</td>\
            <td>"+tian[4]+"</td>\
            <td>"+tian_angan[4]+"</td>\
            <td>"+tian_zhi[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[4]+"</td>\
            <td>"+anzhishi[4]+"</td>\
            <td>"+ren_angan[4]+"</td>\
            <td>"+ren_anzhi[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[4]+"</td>\
            <td>"+di[4]+"</td>\
            <td>"+di_angan[4]+"</td>\
            <td>"+di_zhi[4]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_9>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[9]+"</td>\
            <td>"+liuqin[9]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[9]+"</td>\
            <td>"+tian[9]+"</td>\
            <td>"+tian_angan[9]+"</td>\
            <td>"+tian_zhi[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[9]+"</td>\
            <td>"+anzhishi[9]+"</td>\
            <td>"+ren_angan[9]+"</td>\
            <td>"+ren_anzhi[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[9]+"</td>\
            <td>"+di[9]+"</td>\
            <td>"+di_angan[9]+"</td>\
            <td>"+di_zhi[9]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_2>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[2]+"</td>\
            <td>"+liuqin[2]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[2]+"</td>\
            <td>"+tian[2]+"</td>\
            <td>"+tian_angan[2]+"</td>\
            <td>"+tian_zhi[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[2]+"</td>\
            <td>"+anzhishi[2]+"</td>\
            <td>"+ren_angan[2]+"</td>\
            <td>"+ren_anzhi[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[2]+"</td>\
            <td>"+di[2]+"</td>\
            <td>"+di_angan[2]+"</td>\
            <td>"+di_zhi[2]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[3]+"</td>\
            <td>宫</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_3>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[3]+"</td>\
            <td>"+liuqin[3]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[3]+"</td>\
            <td>"+tian[3]+"</td>\
            <td>"+tian_angan[3]+"</td>\
            <td>"+tian_zhi[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[3]+"</td>\
            <td>"+anzhishi[3]+"</td>\
            <td>"+ren_angan[3]+"</td>\
            <td>"+ren_anzhi[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[3]+"</td>\
            <td>"+di[3]+"</td>\
            <td>"+di_angan[3]+"</td>\
            <td>"+di_zhi[3]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_5>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[5]+"</td>\
            <td>"+liuqin[5]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[5]+"</td>\
            <td>"+tian[5]+"</td>\
            <td>"+tian_angan[5]+"</td>\
            <td>"+tian_zhi[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[5]+"</td>\
            <td>"+anzhishi[5]+"</td>\
            <td>"+ren_angan[5]+"</td>\
            <td>"+ren_anzhi[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[5]+"</td>\
            <td>"+di[5]+"</td>\
            <td>"+di_angan[5]+"</td>\
            <td>"+di_zhi[5]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_7>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[7]+"</td>\
            <td>"+liuqin[7]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[7]+"</td>\
            <td>"+tian[7]+"</td>\
            <td>"+tian_angan[7]+"</td>\
            <td>"+tian_zhi[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[7]+"</td>\
            <td>"+anzhishi[7]+"</td>\
            <td>"+ren_angan[7]+"</td>\
            <td>"+ren_anzhi[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[7]+"</td>\
            <td>"+di[7]+"</td>\
            <td>"+di_angan[7]+"</td>\
            <td>"+di_zhi[7]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+wangshuai[7]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_8>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[8]+"</td>\
            <td>"+liuqin[8]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
          </tr>\
          <tr>\
            <td>"+xing[8]+"</td>\
            <td>"+tian[8]+"</td>\
            <td>"+tian_angan[8]+"</td>\
            <td>"+tian_zhi[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[8]+"</td>\
            <td>"+anzhishi[8]+"</td>\
            <td>"+ren_angan[8]+"</td>\
            <td>"+ren_anzhi[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[8]+"</td>\
            <td>"+di[8]+"</td>\
            <td>"+di_angan[8]+"</td>\
            <td>"+di_zhi[8]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_1>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[1]+"</td>\
            <td>"+liuqin[1]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
			</tr>\
          <tr>\
            <td>"+xing[1]+"</td>\
            <td>"+tian[1]+"</td>\
            <td>"+tian_angan[1]+"</td>\
            <td>"+tian_zhi[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[1]+"</td>\
            <td>"+anzhishi[1]+"</td>\
            <td>"+ren_angan[1]+"</td>\
            <td>"+ren_anzhi[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[1]+"</td>\
            <td>"+di[1]+"</td>\
            <td>"+di_angan[1]+"</td>\
            <td>"+di_zhi[1]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_6>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[6]+"</td>\
            <td>"+liuqin[6]+"</td>\
            <td style=\"border:solid 2px red\">"+yue_jian+"</td>\
           <td style=\"border:solid 2px red\">"+ri_jian+"</td>\
			</tr>\
          <tr>\
            <td>"+xing[6]+"</td>\
            <td>"+tian[6]+"</td>\
            <td>"+tian_angan[6]+"</td>\
            <td>"+tian_zhi[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[6]+"</td>\
            <td>"+anzhishi[6]+"</td>\
            <td>"+ren_angan[6]+"</td>\
            <td>"+ren_anzhi[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[6]+"</td>\
            <td>"+di[6]+"</td>\
            <td>"+di_angan[6]+"</td>\
            <td>"+di_zhi[6]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[8]+"</td>\
            <td>宫</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table  border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td>"+wangshuai[1]+"</td>\
            <td>宫</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td>"+wangshuai[6]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
  </tbody>\
</table>\
")
}