function output_panduan(x){
get_tiangan_zuhe(tian[x],di[x])
get_all_shensha(c,x)

document.getElementById("panduan").innerHTML = "\
<table border=1 id=fengong_panduan>\
  <tbody>\
    <tr>\
	 <td>\
      <table>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[x]+"</td>\
            <td>"+liuqin[x]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[x]+"</td>\
            <td>"+tian[x]+"</td>\
            <td>"+tian_angan[x]+"</td>\
            <td>"+tian_zhi[x]+"</td>\
            <td>"+tianpan_guiren[x]+"</td>\
            <td>"+tianzhi_liuqin[x]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[x]+"</td>\
            <td>"+anzhishi[x]+"</td>\
            <td>"+ren_angan[x]+"</td>\
            <td>"+ren_anzhi[x]+"</td>\
            <td>"+renpan_guiren[x]+"</td>\
            <td>"+renzhi_liuqin[x]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[x]+"</td>\
            <td>"+di[x]+"</td>\
            <td>"+di_angan[x]+"</td>\
            <td>"+di_zhi[x]+"</td>\
            <td>"+dipan_guiren[x]+"</td>\
            <td>"+dizhi_liuqin[x]+"</td>\
          </tr>\
          <tr>\
            <td class=di_gong id=digong_" + x + "1></td>\
            <td class=di_gong id=digong_" + x + "2></td>\
            <td class=di_gong id=digong_" + x + "3></td>\
            <td>"+an_liuqin[x]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+dayun_zibai[x]+"</td>\
            <td>"+nian_zibai[x]+"</td>\
            <td>"+yue_zibai[x]+"</td>\
            <td>"+ri_zibai[x]+"</td>\
            <td>"+shi_zibai[x]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
	 <td>\
		<table>\
		<tbody>\
		<tr>\
			<td>"+minggan_zuhe+"</td>\
		</tr>\
		<tr>\
			<td>"+tian_shensha+"</td>\
		</tr>\
		<tr>\
			<td>"+ren_shensha+"</td>\
		</tr>\
		<tr>\
			<td>"+di_shensha+"</td>\
		</tr>\
		<tr>\
			<td></td>\
		</tr>\
		<tr>\
			<td></td>\
		</tr>\
		</tbody>\
		</table>\
	 </td>\
	 </tr>\
	</tbody>\
</table>\
"
}

function output_fei_full(){
document.write("\
<table border=1 id=jumian>\
  <tbody>\
    <tr>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[4]+"</td>\
            <td>宫</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table  border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+wangshuai[9]+"</td>\
            <td>宫</td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+wangshuai[2]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_4>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[4]+"</td>\
            <td>"+liuqin[4]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[4]+"</td>\
            <td>"+tian[4]+"</td>\
            <td>"+tian_angan[4]+"</td>\
            <td>"+tian_zhi[4]+"</td>\
            <td>"+tianpan_guiren[4]+"</td>\
            <td>"+tianzhi_liuqin[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[4]+"</td>\
            <td>"+anzhishi[4]+"</td>\
            <td>"+ren_angan[4]+"</td>\
            <td>"+ren_anzhi[4]+"</td>\
            <td>"+renpan_guiren[4]+"</td>\
            <td>"+renzhi_liuqin[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[4]+"</td>\
            <td>"+di[4]+"</td>\
            <td>"+di_angan[4]+"</td>\
            <td>"+di_zhi[4]+"</td>\
            <td>"+dipan_guiren[4]+"</td>\
            <td>"+dizhi_liuqin[4]+"</td>\
          </tr>\
          <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_41>辰</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_42>巽</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_43>巳</td>\
            <td>"+an_liuqin[4]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+dayun_zibai[4]+"</td>\
            <td>"+nian_zibai[4]+"</td>\
            <td>"+yue_zibai[4]+"</td>\
            <td>"+ri_zibai[4]+"</td>\
            <td>"+shi_zibai[4]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_9>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[9]+"</td>\
            <td>"+liuqin[9]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[9]+"</td>\
            <td>"+tian[9]+"</td>\
            <td>"+tian_angan[9]+"</td>\
            <td>"+tian_zhi[9]+"</td>\
            <td>"+tianpan_guiren[9]+"</td>\
            <td>"+tianzhi_liuqin[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[9]+"</td>\
            <td>"+anzhishi[9]+"</td>\
            <td>"+ren_angan[9]+"</td>\
            <td>"+ren_anzhi[9]+"</td>\
            <td>"+renpan_guiren[9]+"</td>\
            <td>"+renzhi_liuqin[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[9]+"</td>\
            <td>"+di[9]+"</td>\
            <td>"+di_angan[9]+"</td>\
            <td>"+di_zhi[9]+"</td>\
            <td>"+dipan_guiren[9]+"</td>\
            <td>"+dizhi_liuqin[9]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_91>丙</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_92>午</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_93>丁</td>\
            <td>"+an_liuqin[9]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[9]+"</td>\
            <td>"+nian_zibai[9]+"</td>\
            <td>"+yue_zibai[9]+"</td>\
            <td>"+ri_zibai[9]+"</td>\
            <td>"+shi_zibai[9]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_2>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[2]+"</td>\
            <td>"+liuqin[2]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[2]+"</td>\
            <td>"+tian[2]+"</td>\
            <td>"+tian_angan[2]+"</td>\
            <td>"+tian_zhi[2]+"</td>\
            <td>"+tianpan_guiren[2]+"</td>\
            <td>"+tianzhi_liuqin[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[2]+"</td>\
            <td>"+anzhishi[2]+"</td>\
            <td>"+ren_angan[2]+"</td>\
            <td>"+ren_anzhi[2]+"</td>\
            <td>"+renpan_guiren[2]+"</td>\
            <td>"+renzhi_liuqin[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[2]+"</td>\
            <td>"+di[2]+"</td>\
            <td>"+di_angan[2]+"</td>\
            <td>"+di_zhi[2]+"</td>\
            <td>"+dipan_guiren[2]+"</td>\
            <td>"+dizhi_liuqin[2]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_21>未</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_22>坤</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_23>申</td>\
            <td>"+an_liuqin[2]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[2]+"</td>\
            <td>"+nian_zibai[2]+"</td>\
            <td>"+yue_zibai[2]+"</td>\
            <td>"+ri_zibai[2]+"</td>\
            <td>"+shi_zibai[2]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[3]+"</td>\
            <td>宫</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_3>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[3]+"</td>\
            <td>"+liuqin[3]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[3]+"</td>\
            <td>"+tian[3]+"</td>\
            <td>"+tian_angan[3]+"</td>\
            <td>"+tian_zhi[3]+"</td>\
            <td>"+tianpan_guiren[3]+"</td>\
            <td>"+tianzhi_liuqin[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[3]+"</td>\
            <td>"+anzhishi[3]+"</td>\
            <td>"+ren_angan[3]+"</td>\
            <td>"+ren_anzhi[3]+"</td>\
            <td>"+renpan_guiren[3]+"</td>\
            <td>"+renzhi_liuqin[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[3]+"</td>\
            <td>"+di[3]+"</td>\
            <td>"+di_angan[3]+"</td>\
            <td>"+di_zhi[3]+"</td>\
            <td>"+dipan_guiren[3]+"</td>\
            <td>"+dizhi_liuqin[3]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_31>甲</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_32>卯</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_33>乙</td>\
            <td>"+an_liuqin[3]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[3]+"</td>\
            <td>"+nian_zibai[3]+"</td>\
            <td>"+yue_zibai[3]+"</td>\
            <td>"+ri_zibai[3]+"</td>\
            <td>"+shi_zibai[3]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_5>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[5]+"</td>\
            <td>"+liuqin[5]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[5]+"</td>\
            <td>"+tian[5]+"</td>\
            <td>"+tian_angan[5]+"</td>\
            <td>"+tian_zhi[5]+"</td>\
            <td>"+tianpan_guiren[5]+"</td>\
            <td>"+tianzhi_liuqin[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[5]+"</td>\
            <td>"+anzhishi[5]+"</td>\
            <td>"+ren_angan[5]+"</td>\
            <td>"+ren_anzhi[5]+"</td>\
            <td>"+renpan_guiren[5]+"</td>\
            <td>"+renzhi_liuqin[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[5]+"</td>\
            <td>"+di[5]+"</td>\
            <td>"+di_angan[5]+"</td>\
            <td>"+di_zhi[5]+"</td>\
            <td>"+dipan_guiren[5]+"</td>\
            <td>"+dizhi_liuqin[5]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_51>戊</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_52>五</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_53>己</td>\
            <td>"+an_liuqin[5]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[5]+"</td>\
            <td>"+nian_zibai[5]+"</td>\
            <td>"+yue_zibai[5]+"</td>\
            <td>"+ri_zibai[5]+"</td>\
            <td>"+shi_zibai[5]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_7>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[7]+"</td>\
            <td>"+liuqin[7]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
           <td class=ext_env>"+ri_jian+"</td>\
		   <td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[7]+"</td>\
            <td>"+tian[7]+"</td>\
            <td>"+tian_angan[7]+"</td>\
            <td>"+tian_zhi[7]+"</td>\
            <td>"+tianpan_guiren[7]+"</td>\
            <td>"+tianzhi_liuqin[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[7]+"</td>\
            <td>"+anzhishi[7]+"</td>\
            <td>"+ren_angan[7]+"</td>\
            <td>"+ren_anzhi[7]+"</td>\
            <td>"+renpan_guiren[7]+"</td>\
            <td>"+renzhi_liuqin[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[7]+"</td>\
            <td>"+di[7]+"</td>\
            <td>"+di_angan[7]+"</td>\
            <td>"+di_zhi[7]+"</td>\
            <td>"+dipan_guiren[7]+"</td>\
            <td>"+dizhi_liuqin[7]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_71>庚</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_72>酉</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_73>辛</td>\
            <td>"+an_liuqin[7]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[7]+"</td>\
            <td>"+nian_zibai[7]+"</td>\
            <td>"+yue_zibai[7]+"</td>\
            <td>"+ri_zibai[7]+"</td>\
            <td>"+shi_zibai[7]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+wangshuai[7]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_8>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[8]+"</td>\
            <td>"+liuqin[8]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
          <tr>\
            <td>"+xing[8]+"</td>\
            <td>"+tian[8]+"</td>\
            <td>"+tian_angan[8]+"</td>\
            <td>"+tian_zhi[8]+"</td>\
            <td>"+tianpan_guiren[8]+"</td>\
            <td>"+tianzhi_liuqin[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[8]+"</td>\
            <td>"+anzhishi[8]+"</td>\
            <td>"+ren_angan[8]+"</td>\
            <td>"+ren_anzhi[8]+"</td>\
            <td>"+renpan_guiren[8]+"</td>\
            <td>"+renzhi_liuqin[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[8]+"</td>\
            <td>"+di[8]+"</td>\
            <td>"+di_angan[8]+"</td>\
            <td>"+di_zhi[8]+"</td>\
            <td>"+dipan_guiren[8]+"</td>\
            <td>"+dizhi_liuqin[8]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_81>丑</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_82>艮</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_83>寅</td>\
            <td>"+an_liuqin[8]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[8]+"</td>\
            <td>"+nian_zibai[8]+"</td>\
            <td>"+yue_zibai[8]+"</td>\
            <td>"+ri_zibai[8]+"</td>\
            <td>"+shi_zibai[8]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_1>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[1]+"</td>\
            <td>"+liuqin[1]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
			</tr>\
          <tr>\
            <td>"+xing[1]+"</td>\
            <td>"+tian[1]+"</td>\
            <td>"+tian_angan[1]+"</td>\
            <td>"+tian_zhi[1]+"</td>\
            <td>"+tianpan_guiren[1]+"</td>\
            <td>"+tianzhi_liuqin[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[1]+"</td>\
            <td>"+anzhishi[1]+"</td>\
            <td>"+ren_angan[1]+"</td>\
            <td>"+ren_anzhi[1]+"</td>\
            <td>"+renpan_guiren[1]+"</td>\
            <td>"+renzhi_liuqin[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[1]+"</td>\
            <td>"+di[1]+"</td>\
            <td>"+di_angan[1]+"</td>\
            <td>"+di_zhi[1]+"</td>\
            <td>"+dipan_guiren[1]+"</td>\
            <td>"+dizhi_liuqin[1]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_11>壬</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_12>子</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_13>癸</td>\
            <td>"+an_liuqin[1]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[1]+"</td>\
            <td>"+nian_zibai[1]+"</td>\
            <td>"+yue_zibai[1]+"</td>\
            <td>"+ri_zibai[1]+"</td>\
            <td>"+shi_zibai[1]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=fei_6>\
        <tbody>\
          <tr>\
            <td>"+tian_shen[6]+"</td>\
            <td>"+liuqin[6]+"</td>\
            <td class=ext_env>"+yue_jian+"</td>\
            <td class=ext_env>"+ri_jian+"</td>\
			<td></td>\
			<td></td>\
			</tr>\
          <tr>\
            <td>"+xing[6]+"</td>\
            <td>"+tian[6]+"</td>\
            <td>"+tian_angan[6]+"</td>\
            <td>"+tian_zhi[6]+"</td>\
            <td>"+tianpan_guiren[6]+"</td>\
            <td>"+tianzhi_liuqin[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+men[6]+"</td>\
            <td>"+anzhishi[6]+"</td>\
            <td>"+ren_angan[6]+"</td>\
            <td>"+ren_anzhi[6]+"</td>\
            <td>"+renpan_guiren[6]+"</td>\
            <td>"+renzhi_liuqin[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[6]+"</td>\
            <td>"+di[6]+"</td>\
            <td>"+di_angan[6]+"</td>\
            <td>"+di_zhi[6]+"</td>\
            <td>"+dipan_guiren[6]+"</td>\
            <td>"+dizhi_liuqin[6]+"</td>\
          </tr>\
         <tr>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_61>戌</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_62>乾</td>\
            <td class=di_gong onclick='shashui(this.id)' id=digong_63>亥</td>\
            <td>"+an_liuqin[6]+"</td>\
			<td></td>\
			<td></td>\
          </tr>\
         <tr>\
            <td>"+dayun_zibai[6]+"</td>\
            <td>"+nian_zibai[6]+"</td>\
            <td>"+yue_zibai[6]+"</td>\
            <td>"+ri_zibai[6]+"</td>\
            <td>"+shi_zibai[6]+"</td>\
			<td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
   <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td>"+wangshuai[8]+"</td>\
            <td>宫</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table  border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td>"+wangshuai[1]+"</td>\
            <td>宫</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table border=0>\
        <tbody>\
          <tr>\
            <td>"+wangshuai[6]+"</td>\
            <td>宫</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
  </tbody>\
</table>\
")
}