function output_fei_full(){

document.write("\
<table border=1>\
  <tbody>\
    <tr>\
      <td>\
<div id=4gong>\
      <table id=fei_4>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[4]+"</td>\
            <td>"+zhangsheng_ar[4]+"</td>\
            <td></td>\
            <td>"+liuqin[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[4]+"</td>\
            <td>"+tian_shen[4]+"</td>\
            <td>"+kong[4]+"</td>\
            <td>"+tianpan_dungan[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+ma[4]+"</td>\
            <td>"+xing[4]+"</td>\
            <td>"+tian[4]+"</td>\
            <td>"+tian_zhi[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[4]+"</td>\
            <td>"+men[4]+"</td>\
            <td>"+di[4]+"</td>\
            <td>"+di_zhi[4]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=9gong>\
      <table id=fei_9>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[9]+"</td>\
            <td>"+zhangsheng_ar[9]+"</td>\
            <td></td>\
            <td>"+liuqin[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[9]+"</td>\
            <td>"+tian_shen[9]+"</td>\
            <td>"+kong[9]+"</td>\
            <td>"+tianpan_dungan[9]+"</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[9]+"</td>\
            <td>"+tian[9]+"</td>\
            <td>"+tian_zhi[9]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[9]+"</td>\
            <td>"+men[9]+"</td>\
            <td>"+di[9]+"</td>\
            <td>"+di_zhi[9]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=2gong>\
      <table id=fei_2>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[2]+"</td>\
            <td>"+zhangsheng_ar[2]+"</td>\
            <td></td>\
            <td>"+liuqin[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[2]+"</td>\
            <td>"+tian_shen[2]+"</td>\
            <td>"+kong[2]+"</td>\
            <td>"+tianpan_dungan[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+ma[2]+"</td>\
            <td>"+xing[2]+"</td>\
            <td>"+tian[2]+"</td>\
            <td>"+tian_zhi[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[2]+"</td>\
            <td>"+men[2]+"</td>\
            <td>"+di[2]+"</td>\
            <td>"+di_zhi[2]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
    </tr>\
    <tr>\
      <td>\
<div id=3gong>\
      <table id=fei_3>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[3]+"</td>\
            <td>"+zhangsheng_ar[3]+"</td>\
            <td></td>\
            <td>"+liuqin[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[3]+"</td>\
            <td>"+tian_shen[3]+"</td>\
            <td>"+kong[3]+"</td>\
            <td>"+tianpan_dungan[3]+"</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[3]+"</td>\
            <td>"+tian[3]+"</td>\
            <td>"+tian_zhi[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[3]+"</td>\
            <td>"+men[3]+"</td>\
            <td>"+di[3]+"</td>\
            <td>"+di_zhi[3]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=5gong>\
      <table id=fei_5>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[5]+"</td>\
            <td>"+zhangsheng_ar[5]+"</td>\
            <td></td>\
            <td>"+liuqin[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[5]+"</td>\
            <td>"+tian_shen[5]+"</td>\
            <td>"+kong[5]+"</td>\
            <td>"+tianpan_dungan[5]+"</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[5]+"</td>\
            <td>"+tian[5]+"</td>\
            <td>"+tian_zhi[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[5]+"</td>\
            <td>"+men[5]+"</td>\
            <td>"+di[5]+"</td>\
            <td>"+di_zhi[5]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=7gong>\
      <table id=fei_7>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[7]+"</td>\
            <td>"+zhangsheng_ar[7]+"</td>\
            <td></td>\
            <td>"+liuqin[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[7]+"</td>\
            <td>"+tian_shen[7]+"</td>\
            <td>"+kong[7]+"</td>\
            <td>"+tianpan_dungan[7]+"</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[7]+"</td>\
            <td>"+tian[7]+"</td>\
            <td>"+tian_zhi[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[7]+"</td>\
            <td>"+men[7]+"</td>\
            <td>"+di[7]+"</td>\
            <td>"+di_zhi[7]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
    </tr>\
    <tr>\
      <td>\
<div id=8gong>\
      <table id=fei_8>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[8]+"</td>\
            <td>"+zhangsheng_ar[8]+"</td>\
            <td></td>\
            <td>"+liuqin[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[8]+"</td>\
            <td>"+tian_shen[8]+"</td>\
            <td>"+kong[8]+"</td>\
            <td>"+tianpan_dungan[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+ma[8]+"</td>\
            <td>"+xing[8]+"</td>\
            <td>"+tian[8]+"</td>\
            <td>"+tian_zhi[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[8]+"</td>\
            <td>"+men[8]+"</td>\
            <td>"+di[8]+"</td>\
            <td>"+di_zhi[8]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=1gong>\
      <table id=fei_1>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[1]+"</td>\
            <td>"+zhangsheng_ar[1]+"</td>\
            <td></td>\
            <td>"+liuqin[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[1]+"</td>\
            <td>"+tian_shen[1]+"</td>\
            <td>"+kong[1]+"</td>\
            <td>"+tianpan_dungan[1]+"</td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[1]+"</td>\
            <td>"+tian[1]+"</td>\
            <td>"+tian_zhi[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[1]+"</td>\
            <td>"+men[1]+"</td>\
            <td>"+di[1]+"</td>\
            <td>"+di_zhi[1]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
      <td>\
<div id=6gong>\
      <table id=fei_6>\
        <tbody>\
          <tr>\
            <td>"+an_liuqin[6]+"</td>\
            <td>"+zhangsheng_ar[6]+"</td>\
            <td></td>\
            <td>"+liuqin[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+an[6]+"</td>\
            <td>"+tian_shen[6]+"</td>\
            <td>"+kong[6]+"</td>\
            <td>"+tianpan_dungan[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+ma[6]+"</td>\
            <td>"+xing[6]+"</td>\
            <td>"+tian[6]+"</td>\
            <td>"+tian_zhi[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[6]+"</td>\
            <td>"+men[6]+"</td>\
            <td>"+di[6]+"</td>\
            <td>"+di_zhi[6]+"</td>\
          </tr>\
        </tbody>\
      </table>\
</di>\
      </td>\
    </tr>\
  </tbody>\
</table>\
")
}