function output_yangua(men_fang,fang_men){
document.write("\
<table border=1>\
  <tbody>\
    <tr>\
      <td>\
      <table class=4>\
        <tbody>\
          <tr>\
            <td>"+men_fang[4]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[4]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=9>\
        <tbody>\
          <tr>\
            <td>"+men_fang[9]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[9]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=2>\
        <tbody>\
          <tr>\
            <td>"+men_fang[2]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[2]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table class=3>\
        <tbody>\
          <tr>\
            <td>"+men_fang[3]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[3]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=5>\
        <tbody>\
          <tr>\
            <td>"+men_fang[5]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[5]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=7>\
        <tbody>\
          <tr>\
            <td>"+men_fang[7]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[7]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table class=8>\
        <tbody>\
          <tr>\
            <td>"+men_fang[8]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[8]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=1>\
        <tbody>\
          <tr>\
            <td>"+men_fang[1]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[1]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=6>\
        <tbody>\
          <tr>\
            <td>"+men_fang[6]+"</td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td></td>\
            <td></td>\
            <td>"+fang_men[6]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
  </tbody>\
</table>\
")
}