function output_zhuan(){
document.write("\
<table border=1>\
  <tbody>\
    <tr>\
      <td>\
      <table class=4>\
        <tbody>\
          <tr>\
            <td>"+an[4]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[4]+"</td>\
            <td>"+tian_shen[4]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+ma[4]+"</td>\
            <td>"+xing[4]+"</td>\
            <td>"+dai_gan[4]+"</td>\
            <td>"+tian[4]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[4]+"</td>\
            <td>"+men[4]+"</td>\
            <td></td>\
            <td>"+di[4]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=9>\
        <tbody>\
          <tr>\
            <td>"+an[9]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[9]+"</td>\
            <td>"+tian_shen[5]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[5]+"</td>\
            <td>"+dai_gan[5]+"</td>\
            <td>"+tian[5]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[5]+"</td>\
            <td>"+men[5]+"</td>\
            <td></td>\
            <td>"+di[9]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=2>\
        <tbody>\
          <tr>\
            <td>"+an[2]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[2]+"</td>\
            <td>"+tian_shen[6]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+ma[2]+"</td>\
            <td>"+xing[6]+"</td>\
            <td>"+dai_gan[6]+"</td>\
            <td>"+tian[6]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[6]+"</td>\
            <td>"+men[6]+"</td>\
            <td>"+di[5]+"</td>\
            <td>"+di[2]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table class=3>\
        <tbody>\
          <tr>\
            <td>"+an[3]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[3]+"</td>\
            <td>"+tian_shen[3]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[3]+"</td>\
            <td>"+dai_gan[3]+"</td>\
            <td>"+tian[3]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[3]+"</td>\
            <td>"+men[3]+"</td>\
            <td></td>\
            <td>"+di[3]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=5>\
        <tbody>\
          <tr>\
            <td>"+an[5]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>&nbsp;&nbsp;</td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td>&nbsp;&nbsp;</td>\
            <td>&nbsp;&nbsp;</td>\
          </tr>\
          <tr>\
            <td>&nbsp;&nbsp;</td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
            <td>"+di[5]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=7>\
        <tbody>\
          <tr>\
            <td>"+an[7]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[7]+"</td>\
            <td>"+tian_shen[7]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[7]+"</td>\
            <td>"+dai_gan[7]+"</td>\
            <td>"+tian[7]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[7]+"</td>\
            <td>"+men[7]+"</td>\
            <td></td>\
            <td>"+di[7]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
    <tr>\
      <td>\
      <table class=8>\
        <tbody>\
          <tr>\
            <td>"+an[8]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[8]+"</td>\
            <td>"+tian_shen[2]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+ma[8]+"</td>\
            <td>"+xing[2]+"</td>\
            <td>"+dai_gan[2]+"</td>\
            <td>"+tian[2]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[2]+"</td>\
            <td>"+men[2]+"</td>\
            <td></td>\
            <td>"+di[8]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=1>\
        <tbody>\
          <tr>\
            <td>"+an[1]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[1]+"</td>\
            <td>"+tian_shen[1]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td></td>\
            <td>"+xing[1]+"</td>\
            <td>"+dai_gan[1]+"</td>\
            <td>"+tian[1]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[1]+"</td>\
            <td>"+men[1]+"</td>\
            <td></td>\
            <td>"+di[1]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
      <td>\
      <table class=6>\
        <tbody>\
          <tr>\
            <td>"+an[6]+"</td>\
            <td></td>\
            <td>&nbsp;&nbsp;</td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+kong[6]+"</td>\
            <td>"+tian_shen[8]+"</td>\
            <td></td>\
            <td></td>\
          </tr>\
          <tr>\
            <td>"+ma[6]+"</td>\
            <td>"+xing[8]+"</td>\
            <td>"+dai_gan[8]+"</td>\
            <td>"+tian[8]+"</td>\
          </tr>\
          <tr>\
            <td>"+di_shen[8]+"</td>\
            <td>"+men[8]+"</td>\
            <td></td>\
            <td>"+di[6]+"</td>\
          </tr>\
        </tbody>\
      </table>\
      </td>\
    </tr>\
  </tbody>\
</table>\
")
}